import type { DiscoverProfile, Group, Event } from '@/types';

export const SEED_PROFILES: DiscoverProfile[] = [
  {
    id: 'user-1',
    name: 'Maya Chen',
    email: 'maya@example.com',
    avatar: '',
    photos: [],
    identity: 'deaf',
    communicationPreferences: ['asl', 'text_only'],
    comfortPreferences: ['small_group', 'quiet_spaces'],
    interests: ['Art', 'Photography', 'Hiking', 'Cooking'],
    bio: {
      perfectHangout: 'A quiet coffee shop with great pastries',
      communicationStyle: 'Fluent ASL signer, love visual conversations',
      lookingForFriend: 'explore art galleries and go on nature walks with',
    },
    location: { city: 'Dallas, TX', radiusMiles: 15, lat: 32.7767, lng: -96.797 },
    availability: ['weekends', 'after_school'],
    ageRange: '16-18',
    safetySettings: { showToHearingAllies: true, allowGroupInvites: true, showASLLearners: true },
    onboardingComplete: true,
    createdAt: '2024-01-15T10:00:00Z',
    distance: 3.2,
    matchScore: 92,
  },
  {
    id: 'user-2',
    name: 'Jordan Rivera',
    email: 'jordan@example.com',
    avatar: '',
    photos: [],
    identity: 'hoh',
    communicationPreferences: ['asl', 'lip_reading'],
    comfortPreferences: ['one_on_one', 'small_group'],
    interests: ['Gaming', 'Robotics', 'Coding', 'Anime'],
    bio: {
      perfectHangout: 'Gaming sessions with snacks and good vibes',
      communicationStyle: 'Mix of ASL and lip reading',
      lookingForFriend: 'play games and build cool projects with',
    },
    location: { city: 'Fort Worth, TX', radiusMiles: 20, lat: 32.7555, lng: -97.3308 },
    availability: ['after_school', 'evenings'],
    ageRange: '15-17',
    safetySettings: { showToHearingAllies: true, allowGroupInvites: true, showASLLearners: true },
    onboardingComplete: true,
    createdAt: '2024-01-20T10:00:00Z',
    distance: 5.7,
    matchScore: 87,
  },
  {
    id: 'user-3',
    name: 'Aisha Thompson',
    email: 'aisha@example.com',
    avatar: '',
    photos: [],
    identity: 'deaf',
    communicationPreferences: ['asl'],
    comfortPreferences: ['big_group', 'small_group'],
    interests: ['Dance', 'Fashion', 'Music', 'Volunteering'],
    bio: {
      perfectHangout: 'Dance practice then smoothies after',
      communicationStyle: 'ASL is my first language!',
      lookingForFriend: 'dance, shop, and just have fun with',
    },
    location: { city: 'Arlington, TX', radiusMiles: 10, lat: 32.7357, lng: -97.1081 },
    availability: ['weekends', 'anytime'],
    ageRange: '16-18',
    safetySettings: { showToHearingAllies: false, allowGroupInvites: true, showASLLearners: false },
    onboardingComplete: true,
    createdAt: '2024-02-01T10:00:00Z',
    distance: 8.1,
    matchScore: 78,
  },
  {
    id: 'user-4',
    name: 'Ethan Park',
    email: 'ethan@example.com',
    avatar: '',
    photos: [],
    identity: 'hearing_ally',
    communicationPreferences: ['learning_asl', 'text_only'],
    comfortPreferences: ['one_on_one', 'quiet_spaces'],
    interests: ['Reading', 'Science', 'Board Games', 'Nature'],
    bio: {
      perfectHangout: 'Board game cafe or a quiet park',
      communicationStyle: 'Learning ASL — patient and enthusiastic',
      lookingForFriend: 'practice ASL and explore new hobbies with',
    },
    location: { city: 'Plano, TX', radiusMiles: 15, lat: 33.0198, lng: -96.6989 },
    availability: ['weekends', 'evenings'],
    ageRange: '16-17',
    safetySettings: { showToHearingAllies: true, allowGroupInvites: true, showASLLearners: true },
    onboardingComplete: true,
    createdAt: '2024-02-10T10:00:00Z',
    distance: 12.4,
    matchScore: 71,
  },
  {
    id: 'user-5',
    name: 'Lily Nguyen',
    email: 'lily@example.com',
    avatar: '',
    photos: [],
    identity: 'deaf',
    communicationPreferences: ['asl', 'written_notes'],
    comfortPreferences: ['small_group', 'quiet_spaces'],
    interests: ['Writing', 'Yoga', 'Pets', 'Cooking'],
    bio: {
      perfectHangout: 'Cozy bookstore vibes with a good friend',
      communicationStyle: 'Native ASL, also love passing notes',
      lookingForFriend: 'write stories and cook new recipes with',
    },
    location: { city: 'Irving, TX', radiusMiles: 10, lat: 32.814, lng: -96.9489 },
    availability: ['after_school', 'weekends'],
    ageRange: '15-16',
    safetySettings: { showToHearingAllies: true, allowGroupInvites: false, showASLLearners: true },
    onboardingComplete: true,
    createdAt: '2024-02-15T10:00:00Z',
    distance: 6.8,
    matchScore: 85,
  },
  {
    id: 'user-6',
    name: 'Marcus Johnson',
    email: 'marcus@example.com',
    avatar: '',
    photos: [],
    identity: 'hoh',
    communicationPreferences: ['lip_reading', 'text_only', 'learning_asl'],
    comfortPreferences: ['big_group', 'one_on_one'],
    interests: ['Basketball', 'Fitness', 'Movies', 'Skateboarding'],
    bio: {
      perfectHangout: 'Pickup basketball then watching movies',
      communicationStyle: 'Lip reading mostly, picking up ASL',
      lookingForFriend: 'play sports and watch movies with',
    },
    location: { city: 'Garland, TX', radiusMiles: 20, lat: 32.9126, lng: -96.6389 },
    availability: ['anytime'],
    ageRange: '17-18',
    safetySettings: { showToHearingAllies: true, allowGroupInvites: true, showASLLearners: true },
    onboardingComplete: true,
    createdAt: '2024-03-01T10:00:00Z',
    distance: 9.5,
    matchScore: 74,
  },
];

export const SEED_GROUPS: Group[] = [
  {
    id: 'group-1',
    name: 'Deaf Teens DFW',
    description: 'A community for Deaf and HoH teens in the Dallas-Fort Worth area. Share experiences, plan meetups, and make lasting friendships!',
    city: 'Dallas-Fort Worth, TX',
    tags: ['Deaf Community', 'Teens', 'Social', 'DFW'],
    rules: ['Be respectful', 'ASL-friendly communication', 'No bullying', 'Keep it fun!'],
    type: 'public',
    members: ['user-1', 'user-2', 'user-3', 'user-5'],
    admins: ['user-1'],
    pinnedPosts: [
      {
        id: 'post-1',
        groupId: 'group-1',
        authorId: 'user-1',
        content: 'Welcome to Deaf Teens DFW! Introduce yourself and share your favorite hobby.',
        isPinned: true,
        createdAt: '2024-01-15T10:00:00Z',
      },
    ],
    avatar: '',
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'group-2',
    name: 'ASL Learners + Deaf Friends',
    description: 'A supportive space where ASL learners can practice with Deaf friends. Everyone is welcome — patience and kindness are key!',
    city: 'Dallas, TX',
    tags: ['ASL', 'Learning', 'Practice', 'Inclusive'],
    rules: ['Be patient with learners', 'Encourage each other', 'No judgment', 'Have fun learning'],
    type: 'public',
    members: ['user-1', 'user-4', 'user-5'],
    admins: ['user-4'],
    pinnedPosts: [],
    avatar: '',
    createdAt: '2024-02-01T10:00:00Z',
  },
  {
    id: 'group-3',
    name: 'Robotics + STEM',
    description: 'For Deaf/HoH students passionate about robotics, coding, science, and tech. Share projects, ask questions, and collaborate!',
    city: 'Fort Worth, TX',
    tags: ['STEM', 'Robotics', 'Coding', 'Science'],
    rules: ['Share your projects', 'Help each other', 'Stay on topic', 'No spam'],
    type: 'request_to_join',
    members: ['user-2', 'user-4'],
    admins: ['user-2'],
    pinnedPosts: [],
    avatar: '',
    createdAt: '2024-02-15T10:00:00Z',
  },
];

export const SEED_EVENTS: Event[] = [
  {
    id: 'event-1',
    title: 'ASL Game Night',
    description: 'Join us for a fun evening of board games and card games — all in ASL! Snacks provided. Beginners welcome.',
    location: 'Dallas Community Center, Dallas TX',
    date: '2026-03-20',
    time: '6:00 PM',
    tags: ['ASL-friendly', 'Quiet Place', 'Games'],
    communicationSupport: 'ASL interpreters available',
    organizerId: 'user-1',
    rsvps: ['user-1', 'user-2', 'user-5'],
    createdAt: '2024-03-01T10:00:00Z',
  },
  {
    id: 'event-2',
    title: 'Deaf Coffee Chat',
    description: 'Casual meet-up at a deaf-friendly cafe. Come hang out, practice ASL, or just chill with new friends!',
    location: 'Quiet Beans Cafe, Fort Worth TX',
    date: '2026-03-25',
    time: '3:00 PM',
    tags: ['Quiet Place', 'ASL-friendly', 'Casual'],
    organizerId: 'user-3',
    rsvps: ['user-3', 'user-1'],
    createdAt: '2024-03-05T10:00:00Z',
  },
  {
    id: 'event-3',
    title: 'STEM Workshop: Intro to Arduino',
    description: 'Hands-on workshop building simple circuits with Arduino. Captioned presentations and visual instructions provided.',
    location: 'Plano Library MakerSpace, Plano TX',
    date: '2026-04-05',
    time: '10:00 AM',
    tags: ['Captioned Venue', 'STEM', 'Workshop'],
    communicationSupport: 'Captioned slides, visual demos',
    organizerId: 'user-2',
    rsvps: ['user-2', 'user-4'],
    createdAt: '2024-03-10T10:00:00Z',
  },
];
